In [2]:
import numpy as np


In [6]:
#1
x =  np.arange(1,13).reshape((6,2)) 
print(x)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [24]:
#2
b = np.arange(10,37).reshape((3,3,3))
dtype=np.float64
print(b)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


In [26]:
#5
z = np.zeros((4,5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
#6
arr = np.zeros(10)
print(arr)
print("Update sixth value and eight valye")
arr[4] = 10
arr[7] = 20
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value and eight valye
[ 0.  0.  0.  0. 10.  0.  0. 20.  0.  0.]


In [29]:
#4
my_array = np.arange(9).reshape(3, 3)
print("Original array:")
print(my_array)
my_array[:,[0, 1]] = my_array[:,[1, 0]]
print("\nAfter swapping arrays:")
print(my_array)

Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

After swapping arrays:
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [30]:
#8
#using no.full
x = np.full((2, 5), 6, dtype=np.uint)
print(x)
#using no.ones
y = np.ones([2, 5], dtype=np.uint) *6
print(y)

[[6 6 6 6 6]
 [6 6 6 6 6]]
[[6 6 6 6 6]
 [6 6 6 6 6]]


In [34]:
#7
z = np.zeros((4))
dtype=np.int64
print (z , "dtype" , dtype)

[0. 0. 0. 0.] dtype <class 'numpy.int64'>


In [39]:
#9
a = np.arange(2,100,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [43]:
#10
arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
brr = np.array([1,2,3])
subt = arr - brr
print(subt)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [45]:
#11
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_values = (arr%2 == 1) 
arr[odd_values] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [57]:
#12
array1 = np.array([[1, 2, 3], [1,2,3], [1,2,3]])
array2 = np.array([[1,1,1], [2,2,2], [3,3,3]])
 
# Stack arrays in sequence horizontally (column wise).
arrayH = np.hstack((array1, array2))
print(arrayH)

[[1 2 3 1 1 1]
 [1 2 3 2 2 2]
 [1 2 3 3 3 3]]


In [58]:
#13
arr = np.array([2, 6, 1, 9, 10, 3, 27])
newArr = arr[(arr > 5) & (arr < 10)]
print(newArr)

[6 9]


In [62]:
#14
print("Creating 8X3 array using numpy.arange")
sampleArray = np.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8,3)
print (sampleArray)

print("\nDividing 8X3 array into 4 sub array\n")
subArrays = np.split(sampleArray, 4) 
print(subArrays)

Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [23]:
#15
import numpy as np
x = np.array([[ 8,  2, -2],[-4,  1,  7],[ 6,  3,  9]])
x[x[:,1].argsort(), :] # Sort by second column


    


array([[-4,  1,  7],
       [ 8,  2, -2],
       [ 6,  3,  9]])

In [36]:
#16
x = np.array([1, 2, 3])
y = np.array([2, 3, 4])
print("Original arrays:")
print(x)
print(y)
print("Sequence of arrays along a new axis:")
print(np.vstack((x, y)))
x = np.array([[1], [2], [3]])
y = np.array([[2], [3], [4]])
print("\nOriginal arrays:")
print(x)
print()
print(y)
print("Sequence of arrays along depth:")
print(np.dstack((x, y)))


Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along depth:
[[[1 2]]

 [[2 3]]

 [[3 4]]]


In [39]:
#17
 a = np.arange(1,10*10+1).reshape((10,10))
print(np.where(a / 5 == 'yes'))

IndentationError: unexpected indent (<ipython-input-39-ccae1a7b52cb>, line 2)